#!/usr/bin/env bash
# Bash script to display "Best School" 10 times,
# with "bad luck" at line 4 and "good luck" at line 8

for i in {1..10}
do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
done
